stages:
  - deploy

deploy-production:
  stage: deploy
  only:
    - main
  script:
    - source ~/.bash_profile
    - cd ~/brag2026
    - git pull origin main
    - npm ci
    - npm run build
    - pm2 restart brag2026
    - echo "Deploy selesai $(date)"
